---
sampler: !obj:selene_sdk.samplers.RandomPositionsSampler {
    target_path: ../data/ce10.sorted_data.all.bed.gz,
    reference_sequence: !obj:selene_sdk.sequences.Genome {
        input_path: ../data/ce10.fa,
        blacklist_regions: ../data/ce10.blacklist.bed.gz
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: distinct_features.caenorhabditis_elegans.txt
    },
    output_dir: ./,
    test_holdout: [chrII],
    validation_holdout: [chrIII],
    seed: 1337,
    sequence_length: 4095,
    step_size: 1,
    bins_start:  2047,
    bins_end: 2048,
    bin_size: 1,
    mode: validate,
    feature_thresholds: 1,
}
batch_size: 64
n_features: 826
output_dir: ../data
random_seed: 1337
create_subdirectory: False
...
